DELETE FROM ModifierArguments WHERE ModifierId = 'MINOR_CIV_TRADE_MEDIUM_INFLUENCE_BONUS_LIGHTHOUSE';

DELETE FROM ModifierArguments WHERE ModifierId = 'MINOR_CIV_TRADE_YIELD_FOR_LIGHTHOUSE';

DELETE FROM ModifierArguments WHERE ModifierId = 'MINOR_CIV_TRADE_LARGE_INFLUENCE_BONUS_SHIPYARD';

DELETE FROM ModifierArguments WHERE ModifierId = 'MINOR_CIV_TRADE_YIELD_FOR_SHIPYARD';